version: '3.0'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    ports:
      - '3000:3000'

volumes:
  web:
