version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  web:
    docker:
      - image: cimg/node:19.3.0
    environment:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      PLAYWRIGHT_BROWSERS_PATH: 0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          command: yarn run test:ci
      - codecov/upload:
          file: './coverage/clover.xml'
          conf: './codecov.yml'
  web-e2e:
    docker:
      - image: mcr.microsoft.com/playwright:v1.21.0-focal
    environment:
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
      PLAYWRIGHT_BROWSERS_PATH: 0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          command: yarn install --frozen-lockfile
      - run:
          command: npx playwright install
      - run:
          command: yarn build
      - run:
          command: yarn test:e2e
          no_output_timeout: 60m
workflows:
  build_and_test:
    jobs:
      - web
      - web-e2e
