name: "publish"
on:
  push:
    branches:
      - release

env:
  API_ENDPOINT: $API_ENDPOINT
  WEB_SOCKET_URL: $WEB_SOCKET_URL
  API: $API
  CDN: $CDN
  CDN_URL_HOST: $CDN_URL_HOST
  GITHUB_CLIENT_ID: $GH_CLIENT_ID
  GITHUB_TOKEN: $GH_TOKEN
  NEXT_PUBLIC_FATHOM_URL: $NEXT_PUBLIC_FATHOM_URL
  NEXT_PUBLIC_DOMAIN_NAME: https://a11ywatch.com
  NEXT_PUBLIC_FATHOM_CODE: $NEXT_PUBLIC_FATHOM_CODE
  NEXT_PUBLIC_MANAGE_BILLING_URL: $NEXT_PUBLIC_MANAGE_BILLING_URL
  NEXT_PUBLIC_REWARDS: $NEXT_PUBLIC_REWARDS
  NEXT_PUBLIC_FREE_TRIAL: $NEXT_PUBLIC_FREE_TRIAL
  STRIPE_KEY: $STRIPE_KEY
  BLOG_WEBFLOW_URL: $BLOG_WEBFLOW_URL
  GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
  IMAGES_UNOPTIMIZED: true

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.12.0"
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf gcc cmake libc6 openssl libssl-dev npm pkg-config g++ ca-certificates
      - uses: tauri-apps/tauri-action@v0.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_PUBLIC_KEY: ${{ secrets.TAURI_PUBLIC_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: app-v__VERSION__
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
